@trigger=any

POST http://localhost:4000/api/v1/users
Content-Type: application/json

{
    "username": "Subashkarki",
    "email": "subashkarki68@gmail.com",
    "name": "Subash",
    "age": 10,
    "password": "1223",
    "repeat_password": "1223"
}