@hostname = http://localhost
@port = 4000
@host = {{hostname}}:{{port}}
@apiUrl = {{host}}/api/v1
@contentType = application/json

# ##
# @prompt username
# @prompt refCode Your reference code display on webpage
# @prompt otp Your one-time password in your mailbox

###
GET {{apiUrl}}/blogs

###

GET {{apiUrl}}/blogs/2

###

POST {{apiUrl}}/blogs
Content-Type: application/json

{
    "msg": "hello",
    "welom": "okay"
}

###
PATCH {{apiUrl}}/blogs/2
Content-Type: application/json

{
    "hello":"World"
}

###
GET {{apiUrl}}/users/subash2
x-roles: admin

###
POST {{apiUrl}}/users
Content-Type: application/json
x-roles: admin

{
    "username": "22aa",
    "email": "kark22i@gmail.com",
    "name": "Subash",
    "age": 19,
    "password": "1223",
    "repeat_password": "1223"
}

###
PATCH  {{apiUrl}}/users/3
Content-Type: application/json
x-roles: readOnly

###
PATCH  {{apiUrl}}/users/3
Content-Type: application/json
x-roles: superadmin

{
    "username": "Subakrki"
}

###
DELETE {{apiUrl}}/users/2
Content-Type: application/json
x-roles: ReadOnly

###
DELETE {{apiUrl}}/users/2
Content-Type: application/json
x-roles: admin,staff
 