@hostname = http://localhost
@port = 3000
@host = {{hostname}}:{{port}}
@apiUrl = {{host}}/api/v1
@contentType = application/json

# ##
# @prompt username
# @prompt refCode Your reference code display on webpage
# @prompt otp Your one-time password in your mailbox

###
GET {{apiUrl}}/blogs

###

GET {{apiUrl}}/blogs/2

###

POST {{apiUrl}}/blogs
Content-Type: application/json

{
    "msg": "hello",
    "welom": "okay"
}

###
PATCH {{apiUrl}}/blogs/2
Content-Type: application/json

{
    "hello":"World"
}

###
GET {{apiUrl}}/users

###
GET {{apiUrl}}/users/subash2
x-roles: admin

###
POST {{apiUrl}}/users/register
Content-Type: application/json
x-roles: admin

{
    "email": "subashkarki68@gmail.com",
    "name": "subash2karki",
    "password": "1223",
    "roles" : ["admin","user"]
}

###
POST {{apiUrl}}/users/login
Content-Type: application/json
x-roles: admin

{
    "email": "subashkarki68@gmail.com",
    "password": "1223"
}

###
POST {{apiUrl}}/users/login
Content-Type: application/json
x-roles: admin

{
    "email": "subashkarki68@gmail.com",
    "password": "1223"
}

#Post a New User
###

# @prompt username Type a unique username
# @prompt email Type your email
# @prompt name Type your name
# @prompt age Type your age
# @prompt password Your password
# @prompt repeat_password Repeat Password
POST {{apiUrl}}/users
Content-Type: application/json
x-roles: admin

{
    "username": "{{username}}",
    "email": "{{email}}",
    "name": "{{name}}",
    "age": "{{age}}",
    "password": "{{password}}",
    "repeat_password": "{{repeat_password}}"
}

###
PATCH  {{apiUrl}}/users/3
Content-Type: application/json
x-roles: readOnly

###
PATCH  {{apiUrl}}/users/Subakrki
Content-Type: application/json
x-roles: superadmin

{
    "username": "pandapanda"
}

###

# @prompt email Type your email
# @prompt name Type your name
# @prompt password Type password
POST {{apiUrl}}/users
Content-Type: application/json
role: admin

{
    "email": "{{email}}",
    "name": "{{name}}",
    "password": "{{password}}"
}

###
POST {{apiUrl}}/users
Content-Type: application/json
x-roles: admin

{
    "email": "sub2ashka3rr23ki618@gmail.com",
    "name": "Subash KArki",
    "password": "nsakdjhj2kh2k123"
}

###
PUT {{apiUrl}}/users/65d30d76819b4f368b3db37c
Content-Type: application/json
role: admin

{
    "name": "Subash Karki",
    "email": "sk@k.com",
    "password": "2Aaa33"
}

###
PATCH  {{apiUrl}}/users/65d30d76819b4f368b3db37c
Content-Type: application/json
role: admin

{
    "email": "s@ka.com"
}

###
GET  {{apiUrl}}/users/65d30d76819b4f368b3db37c
Content-Type: application/json
x-role: admin

###
DELETE  {{apiUrl}}/users/65d30d76819b4f368b3db37c
Content-Type: application/json
x-role: admin

###
POST {{apiUrl}}/users/generate-fp-token
Content-Type: application/json

{
    "email": "subashkarki68@gmail.com"
}

###
POST {{apiUrl}}/users/verify-fp-token
Content-Type: application/json

{
    "email":"subashkarki68@gmail.com",
    "fpToken": "599805",
    "newPassword": "ball"
}

###
POST {{apiUrl}}/users/change-password
Content-Type: : application/json

{
    "email": "subashkarki68@gmail.com",
    "password": "ball",
    "newPassword": "apple"
}

###
PATCH {{apiUrl}}/users//block-user/byadmin
Content-Type: application/json

{
    "email":""
}

###
GET {{apiUrl}}/users

###
POST {{apiUrl}}/users/registeradmin
x-super-admin-password: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9eyJkYXRhIjp7Il9pZCI6IjY1ZGI0NGFlMzRjYTc5M2U4MDc0OTM1MiIsIm5hbWUiOiJSdWNoaSBSYWogS2Fya2kiLCJwYXNzd29yZCI6IiQyYiQxMCRONnY3dmtEa250ZUhCdG9FYnpocnIuNTdRMi8zTGsxdVFvckpNcnJpYkouQm12MHk1eHNMMiIsImVtYWlsIjoicnVj
Content-Type: application/json

{
    "email": "subashkarki68@gmail.com",
    "name": "Subash Karki",
    "password": "123"
}